apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies-kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: republic
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.3.4         # CHANGEME if you pin a different version
    helm:
      values: |
        # The Law engine. Admission webhook that enforces the Constitution.
        admissionController:
          replicas: 1              # CHANGEME -> 3 for HA
        backgroundController:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
